spring:
  application:
    name: ms-opiniones-service
  profiles:
    active: development
  config:
    import: optional:configserver:http://root:s3cr3t@localhost:7070
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/
